name: Debug Test

on:
  workflow_dispatch: # Manual trigger only

jobs:
  debug-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check if secret exists
      run: |
        if [ -z "$DISCORD_WEBHOOK_URL" ]; then
          echo "❌ DISCORD_WEBHOOK_URL secret is not set!"
          exit 1
        else
          echo "✅ DISCORD_WEBHOOK_URL secret is set"
          echo "Secret length: ${#DISCORD_WEBHOOK_URL}"
        fi
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    - name: Create config from template
      run: |
        cp config.template.json config.json
        python3 << 'EOF'
        import json
        import os
        with open('config.json', 'r') as f:
            config = json.load(f)
        webhook_url = os.environ['DISCORD_WEBHOOK_URL']
        config['notification']['discord_webhook_url'] = webhook_url
        with open('config.json', 'w') as f:
            json.dump(config, f, indent=4)
        print("✅ Config created successfully")
        print(f"Webhook URL configured: {webhook_url[:50]}...")
        EOF
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    - name: Test direct Discord webhook
      run: |
        python3 << 'EOF'
        import requests
        import json
        import os
        from datetime import datetime
        
        webhook_url = os.environ['DISCORD_WEBHOOK_URL']

        embed = {
            "title": "🧪 GitHub Actions Debug Test",
            "description": "Testing from GitHub Actions",
            "color": 0xff0000,
            "timestamp": datetime.now().isoformat(),
            "fields": [
                {
                    "name": "🤖 Source",
                    "value": "GitHub Actions Debug Workflow",
                    "inline": False
                },
                {
                    "name": "⏰ Time",
                    "value": datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
                    "inline": False
                },
                {
                    "name": "🔗 Webhook",
                    "value": f"ID: {webhook_url.split('/')[-2] if '/' in webhook_url else 'Unknown'}",
                    "inline": False
                }
            ]
        }

        payload = {
            "content": "🤖 **GitHub Actions Test**",
            "embeds": [embed]
        }
        
        try:
            response = requests.post(webhook_url, json=payload, timeout=10)
            if response.status_code == 204:
                print("✅ Direct webhook test successful!")
            else:
                print(f"❌ Webhook failed: {response.status_code}")
                print(f"Response: {response.text}")
        except Exception as e:
            print(f"❌ Error: {e}")
        EOF
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    
    - name: Test heartbeat notification
      run: |
        python main.py --test-notification
    
    - name: Test full check with heartbeat
      run: |
        python main.py --check --heartbeat
