name: Website Tracker

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches: [ main ]

jobs:
  track-websites:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create config from template
      run: |
        cp config.template.json config.json
        # Replace webhook URL with secret
        sed -i 's|YOUR_DISCORD_WEBHOOK_URL_HERE|${{ secrets.DISCORD_WEBHOOK_URL }}|g' config.json
      
    - name: Load previous tracking data
      run: |
        # Create empty tracking data if it doesn't exist
        if [ ! -f website_data.json ]; then
          echo '{}' > website_data.json
        fi
    
    - name: Run website tracking
      run: |
        python main.py --check
    
    - name: Commit and push tracking data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add website_data.json
        git diff --staged --quiet || git commit -m "Update tracking data - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
